import React, { useState } from 'react';
import { 
  CheckSquare, 
  Calendar, 
  Clock, 
  AlertCircle, 
  CheckCircle2, 
  Plus, 
  Filter, 
  Phone, 
  Mail, 
  MessageSquare, 
  User, 
  Building, 
  Sparkles,
  ArrowRight,
  Trash2,
  X
} from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { CRMTask, TaskPriority, TaskType, TaskStatus } from '../../types';

export const TasksManager: React.FC = () => {
  const { 
    crmTasks, 
    addCRMTask, 
    updateCRMTaskStatus, 
    deleteCRMTask, 
    agents, 
    properties, 
    unifiedContacts, 
    currentUser 
  } = useApp();

  const [activeTab, setActiveTab] = useState<'today' | 'upcoming' | 'overdue' | 'completed'>('today');
  const [filterAgent, setFilterAgent] = useState<string>('all');
  const [filterType, setFilterType] = useState<string>('all');
  const [filterPriority, setFilterPriority] = useState<string>('all');

  // Add Task Modal State
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [taskTitle, setTaskTitle] = useState('');
  const [taskDescription, setTaskDescription] = useState('');
  const [taskType, setTaskType] = useState<TaskType>('relance');
  const [taskPriority, setTaskPriority] = useState<TaskPriority>('haute');
  const [taskDueDate, setTaskDueDate] = useState(new Date().toISOString().split('T')[0]);
  const [taskDueTime, setTaskDueTime] = useState('11:00');
  const [taskAssignedAgentId, setTaskAssignedAgentId] = useState(currentUser.id);
  const [taskContactId, setTaskContactId] = useState('');
  const [taskPropertyId, setTaskPropertyId] = useState('');

  const todayStr = new Date().toISOString().split('T')[0];

  // Partition tasks
  const isOverdue = (task: CRMTask) => task.status !== 'terminee' && task.dueDate < todayStr;
  const isToday = (task: CRMTask) => task.status !== 'terminee' && task.dueDate === todayStr;
  const isUpcoming = (task: CRMTask) => task.status !== 'terminee' && task.dueDate > todayStr;
  const isCompleted = (task: CRMTask) => task.status === 'terminee';

  const counts = {
    today: crmTasks.filter(isToday).length,
    overdue: crmTasks.filter(isOverdue).length,
    upcoming: crmTasks.filter(isUpcoming).length,
    completed: crmTasks.filter(isCompleted).length
  };

  const currentTabTasks = crmTasks.filter(task => {
    if (activeTab === 'today') return isToday(task);
    if (activeTab === 'overdue') return isOverdue(task);
    if (activeTab === 'upcoming') return isUpcoming(task);
    if (activeTab === 'completed') return isCompleted(task);
    return true;
  }).filter(task => {
    if (filterAgent !== 'all' && task.assignedAgentId !== filterAgent) return false;
    if (filterType !== 'all' && task.type !== filterType) return false;
    if (filterPriority !== 'all' && task.priority !== filterPriority) return false;
    return true;
  });

  const handleCreateTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!taskTitle.trim()) return;

    const assignedAgent = agents.find(a => a.id === taskAssignedAgentId) || { name: currentUser.name };
    const contact = unifiedContacts.find(c => c.id === taskContactId);
    const prop = properties.find(p => p.id === taskPropertyId);

    addCRMTask({
      title: taskTitle,
      description: taskDescription,
      type: taskType,
      priority: taskPriority,
      status: 'a_faire',
      assignedAgentId: taskAssignedAgentId,
      assignedAgentName: assignedAgent.name,
      dueDate: taskDueDate,
      dueTime: taskDueTime || undefined,
      contactId: contact ? contact.id : undefined,
      contactName: contact ? `${contact.firstName} ${contact.lastName}` : undefined,
      propertyId: prop ? prop.id : undefined,
      propertyRef: prop ? prop.ref : undefined,
      isAutoGenerated: false
    });

    setIsAddModalOpen(false);
    resetForm();
  };

  const resetForm = () => {
    setTaskTitle('');
    setTaskDescription('');
    setTaskType('relance');
    setTaskPriority('haute');
    setTaskDueDate(todayStr);
    setTaskDueTime('11:00');
    setTaskContactId('');
    setTaskPropertyId('');
  };

  const priorityBadges: Record<TaskPriority, { label: string; color: string }> = {
    urgente: { label: 'Urgente', color: 'bg-red-100 text-red-800 border-red-200' },
    haute: { label: 'Haute', color: 'bg-amber-100 text-amber-800 border-amber-200' },
    normale: { label: 'Normale', color: 'bg-blue-100 text-blue-800 border-blue-200' },
    basse: { label: 'Basse', color: 'bg-stone-100 text-stone-700 border-stone-200' }
  };

  const typeIcons: Record<TaskType, { label: string; icon: string }> = {
    appel: { label: 'Appel Téléphonique', icon: '📞' },
    relance: { label: 'Relance Client', icon: '🔁' },
    email: { label: 'Email Commercial', icon: '✉️' },
    rendez_vous: { label: 'Rendez-vous', icon: '🤝' },
    visite: { label: 'Visite Terrain', icon: '🔑' },
    mandat: { label: 'Mandat / Expiration', icon: '📜' },
    administratif: { label: 'Administratif / Notaire', icon: '📁' },
    autre: { label: 'Autre', icon: '📌' }
  };

  return (
    <div className="space-y-6">
      
      {/* Top statistics summary */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <button
          onClick={() => setActiveTab('today')}
          className={`p-4 rounded-xl border text-left transition-all cursor-pointer ${
            activeTab === 'today'
              ? 'bg-amber-800 text-white border-amber-900 shadow-md ring-2 ring-amber-800/20'
              : 'bg-white text-stone-800 border-stone-200 hover:border-amber-400'
          }`}
        >
          <div className="flex items-center justify-between mb-1">
            <span className="text-xs font-semibold uppercase tracking-wider opacity-80">Aujourd'hui</span>
            <Clock className="w-4 h-4 opacity-70" />
          </div>
          <div className="text-2xl font-bold font-display">{counts.today}</div>
          <p className="text-[11px] opacity-75 mt-0.5">Tâches à traiter ce jour</p>
        </button>

        <button
          onClick={() => setActiveTab('overdue')}
          className={`p-4 rounded-xl border text-left transition-all cursor-pointer ${
            activeTab === 'overdue'
              ? 'bg-red-800 text-white border-red-900 shadow-md ring-2 ring-red-800/20'
              : 'bg-white text-stone-800 border-stone-200 hover:border-red-400'
          }`}
        >
          <div className="flex items-center justify-between mb-1">
            <span className="text-xs font-semibold uppercase tracking-wider text-red-600 dark:text-red-400">En Retard</span>
            <AlertCircle className="w-4 h-4 text-red-500" />
          </div>
          <div className="text-2xl font-bold font-display text-red-600">{counts.overdue}</div>
          <p className="text-[11px] opacity-75 mt-0.5">Échéance dépassée</p>
        </button>

        <button
          onClick={() => setActiveTab('upcoming')}
          className={`p-4 rounded-xl border text-left transition-all cursor-pointer ${
            activeTab === 'upcoming'
              ? 'bg-stone-900 text-white border-black shadow-md ring-2 ring-stone-900/20'
              : 'bg-white text-stone-800 border-stone-200 hover:border-stone-400'
          }`}
        >
          <div className="flex items-center justify-between mb-1">
            <span className="text-xs font-semibold uppercase tracking-wider opacity-80">À Venir</span>
            <Calendar className="w-4 h-4 opacity-70" />
          </div>
          <div className="text-2xl font-bold font-display">{counts.upcoming}</div>
          <p className="text-[11px] opacity-75 mt-0.5">Jours suivants</p>
        </button>

        <button
          onClick={() => setActiveTab('completed')}
          className={`p-4 rounded-xl border text-left transition-all cursor-pointer ${
            activeTab === 'completed'
              ? 'bg-emerald-800 text-white border-emerald-900 shadow-md ring-2 ring-emerald-800/20'
              : 'bg-white text-stone-800 border-stone-200 hover:border-emerald-400'
          }`}
        >
          <div className="flex items-center justify-between mb-1">
            <span className="text-xs font-semibold uppercase tracking-wider opacity-80">Terminées</span>
            <CheckCircle2 className="w-4 h-4 opacity-70" />
          </div>
          <div className="text-2xl font-bold font-display text-emerald-600">{counts.completed}</div>
          <p className="text-[11px] opacity-75 mt-0.5">Tâches clôturées</p>
        </button>
      </div>

      {/* Filter and Action Bar */}
      <div className="bg-white rounded-xl p-4 border border-stone-200 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-3 text-xs">
        <div className="flex flex-wrap items-center gap-2 flex-1">
          <div className="flex items-center gap-1.5 text-stone-500 font-medium">
            <Filter className="w-3.5 h-3.5 text-stone-400" />
            <span>Filtres :</span>
          </div>

          <select
            value={filterAgent}
            onChange={(e) => setFilterAgent(e.target.value)}
            className="p-1.5 bg-stone-50 border border-stone-200 rounded-lg text-stone-700"
          >
            <option value="all">Tous les agents</option>
            {agents.map(a => (
              <option key={a.id} value={a.id}>{a.name}</option>
            ))}
          </select>

          <select
            value={filterType}
            onChange={(e) => setFilterType(e.target.value)}
            className="p-1.5 bg-stone-50 border border-stone-200 rounded-lg text-stone-700"
          >
            <option value="all">Tous les types</option>
            {(Object.keys(typeIcons) as TaskType[]).map(t => (
              <option key={t} value={t}>{typeIcons[t].label}</option>
            ))}
          </select>

          <select
            value={filterPriority}
            onChange={(e) => setFilterPriority(e.target.value)}
            className="p-1.5 bg-stone-50 border border-stone-200 rounded-lg text-stone-700"
          >
            <option value="all">Toutes priorités</option>
            <option value="urgente">Urgente</option>
            <option value="haute">Haute</option>
            <option value="normale">Normale</option>
            <option value="basse">Basse</option>
          </select>
        </div>

        <button
          onClick={() => setIsAddModalOpen(true)}
          className="inline-flex items-center justify-center gap-1.5 px-4 py-2 bg-amber-800 hover:bg-amber-900 text-white font-semibold rounded-lg shadow-xs transition-colors cursor-pointer shrink-0"
        >
          <Plus className="w-4 h-4" />
          <span>Nouvelle Tâche</span>
        </button>
      </div>

      {/* Tasks Table / Cards */}
      <div className="space-y-3">
        {currentTabTasks.length === 0 ? (
          <div className="bg-white rounded-xl p-12 text-center border border-stone-200">
            <CheckCircle2 className="w-10 h-10 text-stone-300 mx-auto mb-2" />
            <h4 className="text-sm font-semibold text-stone-700">Aucune tâche dans cette section</h4>
            <p className="text-xs text-stone-400 mt-1">Vous êtes à jour dans vos relances et actions commerciales !</p>
          </div>
        ) : (
          currentTabTasks.map(task => {
            const isDone = task.status === 'terminee';

            return (
              <div
                key={task.id}
                className={`p-4 rounded-xl border bg-white transition-all hover:shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-3 ${
                  isOverdue(task) ? 'border-red-300 bg-red-50/20' : 'border-stone-200'
                }`}
              >
                <div className="flex items-start gap-3 flex-1">
                  <button
                    onClick={() => updateCRMTaskStatus(task.id, isDone ? 'a_faire' : 'terminee')}
                    className={`mt-0.5 w-5 h-5 rounded border flex items-center justify-center transition-colors cursor-pointer shrink-0 ${
                      isDone 
                        ? 'bg-emerald-600 border-emerald-600 text-white' 
                        : 'border-stone-300 hover:border-amber-800 bg-stone-50'
                    }`}
                  >
                    {isDone && <CheckCircle2 className="w-3.5 h-3.5" />}
                  </button>

                  <div className="space-y-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="text-base">{typeIcons[task.type]?.icon || '📌'}</span>
                      <h4 className={`text-sm font-bold ${isDone ? 'line-through text-stone-400' : 'text-stone-900'}`}>
                        {task.title}
                      </h4>
                      <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full border ${priorityBadges[task.priority].color}`}>
                        {priorityBadges[task.priority].label}
                      </span>
                      {task.isAutoGenerated && (
                        <span className="text-[10px] font-medium text-amber-800 bg-amber-50 border border-amber-200 px-2 py-0.5 rounded-md flex items-center gap-1">
                          <Sparkles className="w-3 h-3" />
                          Auto J+1
                        </span>
                      )}
                    </div>

                    <p className="text-xs text-stone-600 leading-relaxed">
                      {task.description}
                    </p>

                    <div className="flex flex-wrap items-center gap-3 text-[11px] text-stone-500 pt-1">
                      <span className="flex items-center gap-1">
                        <Calendar className="w-3 h-3 text-stone-400" />
                        Échéance : <strong className={isOverdue(task) ? 'text-red-700' : 'text-stone-700'}>{task.dueDate} {task.dueTime}</strong>
                      </span>
                      <span className="flex items-center gap-1">
                        <User className="w-3 h-3 text-stone-400" />
                        Agent : {task.assignedAgentName}
                      </span>
                      {task.contactName && (
                        <span className="text-amber-900 font-semibold bg-amber-50 px-1.5 py-0.5 rounded">
                          Contact : {task.contactName}
                        </span>
                      )}
                      {task.propertyRef && (
                        <span className="text-stone-700 font-mono bg-stone-100 px-1.5 py-0.5 rounded">
                          Réf : {task.propertyRef}
                        </span>
                      )}
                    </div>
                  </div>
                </div>

                {/* Right action controls */}
                <div className="flex items-center gap-2 self-end md:self-auto shrink-0">
                  {task.status !== 'terminee' && (
                    <button
                      onClick={() => updateCRMTaskStatus(task.id, 'terminee')}
                      className="px-3 py-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-700 rounded-lg text-xs font-semibold border border-emerald-200 transition-colors cursor-pointer"
                    >
                      Terminer
                    </button>
                  )}
                  <button
                    onClick={() => deleteCRMTask(task.id)}
                    className="p-1.5 text-stone-400 hover:text-red-600 rounded-lg hover:bg-stone-50 transition-colors cursor-pointer"
                    title="Supprimer la tâche"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>
            );
          })
        )}
      </div>

      {/* Add Task Modal */}
      {isAddModalOpen && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl max-w-lg w-full p-6 shadow-2xl border border-stone-200 space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-stone-100">
              <div className="flex items-center gap-2">
                <CheckSquare className="w-5 h-5 text-amber-800" />
                <h3 className="text-base font-bold text-stone-900">Programmer une Nouvelle Tâche CRM</h3>
              </div>
              <button onClick={() => setIsAddModalOpen(false)} className="text-stone-400 hover:text-stone-600">
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleCreateTask} className="space-y-4 text-xs">
              <div>
                <label className="font-semibold text-stone-700 block mb-1">Titre de l'action *</label>
                <input
                  type="text"
                  required
                  placeholder="ex: Relance téléphonique après visite Villa Kantaoui"
                  value={taskTitle}
                  onChange={(e) => setTaskTitle(e.target.value)}
                  className="w-full p-2.5 bg-stone-50 border border-stone-200 rounded-lg"
                />
              </div>

              <div>
                <label className="font-semibold text-stone-700 block mb-1">Consignes et objectifs</label>
                <textarea
                  rows={2}
                  placeholder="Objectif de l'appel ou de la démarche..."
                  value={taskDescription}
                  onChange={(e) => setTaskDescription(e.target.value)}
                  className="w-full p-2.5 bg-stone-50 border border-stone-200 rounded-lg"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="font-semibold text-stone-700 block mb-1">Type d'action</label>
                  <select
                    value={taskType}
                    onChange={(e) => setTaskType(e.target.value as any)}
                    className="w-full p-2.5 bg-stone-50 border border-stone-200 rounded-lg"
                  >
                    {(Object.keys(typeIcons) as TaskType[]).map(t => (
                      <option key={t} value={t}>{typeIcons[t].label}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="font-semibold text-stone-700 block mb-1">Priorité</label>
                  <select
                    value={taskPriority}
                    onChange={(e) => setTaskPriority(e.target.value as any)}
                    className="w-full p-2.5 bg-stone-50 border border-stone-200 rounded-lg"
                  >
                    <option value="urgente">🔴 Urgente</option>
                    <option value="haute">🟠 Haute</option>
                    <option value="normale">🔵 Normale</option>
                    <option value="basse">⚪ Basse</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="font-semibold text-stone-700 block mb-1">Date d'échéance *</label>
                  <input
                    type="date"
                    required
                    value={taskDueDate}
                    onChange={(e) => setTaskDueDate(e.target.value)}
                    className="w-full p-2.5 bg-stone-50 border border-stone-200 rounded-lg"
                  />
                </div>
                <div>
                  <label className="font-semibold text-stone-700 block mb-1">Heure recommandée</label>
                  <input
                    type="time"
                    value={taskDueTime}
                    onChange={(e) => setTaskDueTime(e.target.value)}
                    className="w-full p-2.5 bg-stone-50 border border-stone-200 rounded-lg"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="font-semibold text-stone-700 block mb-1">Contact associé (optionnel)</label>
                  <select
                    value={taskContactId}
                    onChange={(e) => setTaskContactId(e.target.value)}
                    className="w-full p-2.5 bg-stone-50 border border-stone-200 rounded-lg"
                  >
                    <option value="">Sélectionner un contact</option>
                    {unifiedContacts.map(c => (
                      <option key={c.id} value={c.id}>{c.firstName} {c.lastName} ({c.ref})</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="font-semibold text-stone-700 block mb-1">Bien concerné (optionnel)</label>
                  <select
                    value={taskPropertyId}
                    onChange={(e) => setTaskPropertyId(e.target.value)}
                    className="w-full p-2.5 bg-stone-50 border border-stone-200 rounded-lg"
                  >
                    <option value="">Sélectionner un bien</option>
                    {properties.map(p => (
                      <option key={p.id} value={p.id}>{p.ref} - {p.title.substring(0, 24)}...</option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="flex justify-end gap-2 pt-3 border-t border-stone-100">
                <button
                  type="button"
                  onClick={() => setIsAddModalOpen(false)}
                  className="px-4 py-2 border border-stone-300 text-stone-700 rounded-lg font-semibold hover:bg-stone-50"
                >
                  Annuler
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 bg-amber-800 hover:bg-amber-900 text-white rounded-lg font-semibold shadow-xs"
                >
                  Créer la Tâche
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

    </div>
  );
};
